### Nova Pessoa Inválida

POST http://localhost:8080/api/v1/users HTTP/1.1
Content-Type: application/json

{
	"nome": "Ciclano de Tal"
}

### Nova Pessoa Válida

POST http://localhost:8080/api/v1/users HTTP/1.1
Content-Type: application/json

{
	"cpf": "76203811041",
	"name": "beltrano de Tal"
}

### Atualizar Pessoa
PUT http://localhost:8080/api/v1/users/1 HTTP/1.1
Content-Type: application/json

{
	"cpf": "76203811041",
	"name": "Zigomar de Tal444"
}



### Listar Pessoas
GET http://localhost:8080/api/v1/users HTTP/1.1

### Ler Pessoa
GET http://localhost:8080/api/v1/users/16536078748 HTTP/1.1

### Excluir Pessoa
DELETE http://localhost:8080/api/v1/users/16536078748 HTTP/1.1


### Ler Pessoa CPF mal-formatado
GET http://localhost:8080/api/v1/users/15678903 HTTP/1.1


### Ler Pessoa CPF mal-formatado

GET http://localhost:8080/api/v1/users/123456q7891 HTTP/1.1
























# ************************

### Listar Doações (Doações é um subrecurso de Pessoa)
GET http://localhost:8080/api/v1/users/16536078748/doacoes HTTP/1.1

### Ler Doação Específica
GET http://localhost:8080/api/v1/users/16536078748/doacoes/2 HTTP/1.1

### Fazer Doação
POST http://localhost:8080/api/v1/users/16536078748/doacoes HTTP/1.1
Content-Type: application/json

{
	"descricao": "Sofá 2 lugares",
	"idCategoria": 1
}

### Ler Doação
GET http://localhost:8080/api/v1/users/16536078748/doacoes/1 HTTP/1.1

### Listar Doações
GET http://localhost:8080/api/v1/users/16536078748/doacoes?limit=10&offset=1 HTTP/1.1
206


### Atualizar doação (IDEMPOTENTE)
PUT http://localhost:8080/api/v1/users/16536078748/doacoes/1
Content-Type: application/json

{
	"descricao": "Sofá 3 lugares",
	"idCategoria": 2
}

### Cancelar doação (NÃO IDEMPOTENTE)
# Geralmente PATCH é usadao para uma transição de estado validada
PATCH http://localhost:8080/api/v1/users/16536078748/doacoes/1
Content-Type: application/json

{
	"operacao": "cancelar",
	"detalhes": {
		
	}
}

### Cancelar
# verbo
PUT http://localhost:8080/api/v1/users/16536078748/doacoes/1/cancelar
# substantivar o verbo
PUT http://localhost:8080/api/v1/users/16536078748/doacoes/1/cancelamentos
